import type { Metadata } from "next";
import localFont from "next/font/local";
import { Rubik } from 'next/font/google';
import "./globals.css";
import Header from "@/components/Header";

const rubikFont = Rubik({ 
  subsets: ['latin'], 
  weight: ["300", "400", "500", "600"],
  variable: '--font-rubik'
});

const cyberFont = localFont({
  src: "./fonts/cybero.ttf",
  variable: "--font-cyber-prime",
  weight: "400 700",
})

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubikFont.variable} ${cyberFont.variable} antialiased`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
